version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .data/postgres-data:/var/lib/postgresql/data

  django:
    working_dir: /app/
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./offisync:/app
    depends_on:
      - db
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    volumes:
      - .data/redis:/data

  celery-worker:
    build: .
    command: celery -A offisync worker --loglevel=info
    volumes:
      - ./offisync:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A offisync beat --loglevel=info --schedule=/var/lib/celery/beat/celerybeat-schedule
    volumes:
      - ./offisync:/app
      - .data/celery-beat-data:/var/lib/celery/beat
    depends_on:
      - redis
