version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - .data/postgres-data:/var/lib/postgresql/data

  django:
    working_dir: /app/
    build: .
    command: >
      /bin/sh -c "
        wait-for db:5432 -- 
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./offisync:/app
      - ./wait-for:/usr/local/bin/wait-for
      - ./.env:/app/.env
    depends_on:
      - db
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    volumes:
      - .data/redis:/data

  celery-worker:
    build: .
    command: celery -A offisync worker --loglevel=info
    volumes:
      - ./offisync:/app
      - ./.env:/app/.env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A offisync beat --loglevel=info --schedule=/var/lib/celery/beat/celerybeat-schedule
    volumes:
      - ./offisync:/app
      - ./.env:/app/.env
      - .data/celery-beat-data:/var/lib/celery/beat
    depends_on:
      - redis
